---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: podman --version
    register: podman_test_output
  - name: podman --version
    debug:
      msg: '{{ podman_test_output.stdout }}'
